"""link categoruy to products

Revision ID: 117b46b1fa9a
Revises: 8d52e0f1bf4a
Create Date: 2018-10-24 15:30:07.731482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117b46b1fa9a'
down_revision = '8d52e0f1bf4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###