"""rename display image for product model

Revision ID: 90bf9d3b03d8
Revises: 117b46b1fa9a
Create Date: 2018-10-25 07:04:13.636567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90bf9d3b03d8'
down_revision = '117b46b1fa9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.String(), nullable=False))
    op.drop_column('products', 'desplay_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('desplay_image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('products', 'image')
    # ### end Alembic commands ###